# Generated by Django 5.1.4 on 2024-12-31 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Categoría')),
            ],
            options={
                'ordering': ('idCategoria',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('talla', models.TextField(verbose_name='Talla')),
            ],
            options={
                'ordering': ('idUsuario',),
            },
        ),
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_lista', models.IntegerField(verbose_name='En lista')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion_scraper.usuario')),
            ],
            options={
                'ordering': ('idUsuario', 'idVestido'),
            },
        ),
        migrations.CreateModel(
            name='Vestido',
            fields=[
                ('idVestido', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('tallas', models.TextField(verbose_name='Tallas')),
                ('color', models.TextField(verbose_name='Color')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('tienda', models.TextField(verbose_name='Tienda')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion_scraper.categoria')),
                ('listas_deseos', models.ManyToManyField(through='fashion_scraper.ListaDeseos', to='fashion_scraper.usuario')),
            ],
            options={
                'ordering': ('idVestido',),
            },
        ),
        migrations.AddField(
            model_name='listadeseos',
            name='idVestido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion_scraper.vestido'),
        ),
    ]
