# Generated by Django 5.1.4 on 2025-01-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
