# Generated by Django 5.1.4 on 2025-01-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_scraper', '0002_alter_usuario_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vestido',
            name='categoria',
        ),
        migrations.AddField(
            model_name='vestido',
            name='categoria',
            field=models.ManyToManyField(to='fashion_scraper.categoria'),
        ),
    ]
