# Generated by Django 5.1.4 on 2025-01-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_scraper', '0003_remove_vestido_categoria_vestido_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestido',
            name='idVestido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
